package net.kipster.terra.init;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.common.base.Optional;
import com.google.common.collect.ImmutableSet;

import net.kipster.terra.Config;
import net.kipster.terra.Config;
import net.kipster.terra.world.biomes.*;

import net.minecraft.world.biome.BiomeForest;
import net.minecraft.world.biome.BiomeTaiga;
import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.common.BiomeDictionary;
import net.minecraftforge.common.BiomeDictionary.Type;
import net.minecraftforge.common.BiomeManager;
import net.minecraftforge.common.BiomeManager.BiomeEntry;
import net.minecraftforge.common.BiomeManager.BiomeType;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class BiomeInit {
	
    public static Set<Biome> presentBiomes;

	public static final Biome TROPICAL_DESERT = new BiomeTropicalDesert();
	public static final Biome GREENEXTREMEHILLS = new BiomeGreenExtremeHills();
	public static final Biome PLATEAU = new BiomePlateau();
    public static final Biome GREENPLATEAU = new BiomeGreenPlateau();
	public static final Biome REDPLATEAU = new BiomeRedPlateau();
	public static final Biome DRYPLATEAU = new BiomeDryPlateau();
	public static final Biome STEPPE = new BiomeSteppe();
	public static final Biome FROZENPLATEAU = new BiomeFrozenPlateau();
	public static final Biome COLDPLATEAU = new BiomeColdPlateau();
	public static final Biome GRASSLAND = new BiomeGrassland();
	public static final Biome FENS = new BiomeFens();
	public static final Biome SHRUBLAND = new BiomeShrubland();
	public static final Biome TUNDRASPIKES = new BiomeTundraSpikes();
	public static final Biome TUNDRA = new BiomeTundra();
	public static final Biome ROCKLAND = new BiomeRockland();
	public static final Biome LAKE = new BiomeLake();
	public static final Biome FROZENLAKE = new BiomeFrozenLake();
	public static final Biome SAHEL = new BiomeSahel();
	public static final Biome SANDSTONEDUNES = new BiomeSandstoneDunes();
	public static final Biome SAND_DUNES = new BiomeSandDunes();
	public static final Biome RED_SAND_DUNES = new BiomeRedSandDunes();
	public static final Biome ORANGE_SAND_DUNES = new BiomeOrangeSandDunes();
	public static final Biome ALPS = new BiomeAlps();
	public static final Biome HIGHLANDS = new BiomeHighlands();
	public static final Biome GLACIER = new BiomeGlacier();
	public static final Biome PINELANDS = new BiomePinelands();
	public static final Biome GREENHILLS = new BiomeGreenHills();
	public static final Biome MEADOW = new BiomeMeadow();
	public static final Biome RAINFOREST = new BiomeRainforest();
	public static final Biome WOODLANDS = new BiomeWoodlands();
	public static final Biome PINKBEACH = new BiomePinkBeach();
	public static final Biome BLACKBEACH = new BiomeBlackBeach();
	public static final Biome PURPLEBEACH = new BiomePurpleBeach();
	public static final Biome REDBEACH = new BiomeRedBeach();
	public static final Biome GREENBEACH = new BiomeGreenBeach();
	public static final Biome ORANGEBEACH = new BiomeOrangeBeach();
	public static final Biome BLACKDESERT = new BiomeBlackDesert();
	public static final Biome BLACKSAND_DUNES = new BiomeBlackSandDunes();
	public static final Biome WHITEBEACH = new BiomeWhiteBeach();
	public static final Biome BLUEMOUNTAIN = new BiomeBlueMountains();
	public static final Biome REDMOUNTAIN = new BiomeRedMountains();
	public static final Biome GREYMOUNTAIN = new BiomeGreyMountains();
	public static final Biome OVERGROWN_PLAINS = new BiomeOvergrownPlains();
	public static final Biome LUSH_SWAMP = new BiomeLushSwamp();
	public static final Biome THICKET = new BiomeThicket();
	public static final Biome BLOSSOM_WOODS = new BiomeBlossomWoods();
	public static final Biome BLUE_TAIGA = new BiomeBlueTaiga();
	public static final Biome COLD_BLUE_TAIGA = new BiomeColdBlueTaiga();
	public static final Biome COLD_DESERT = new BiomeColdDesert();
	public static final Biome MYSTIC_WOODS = new BiomeMysticWoods();
	public static final Biome SPRUCE_WOODS = new BiomeSpruceWoods();
	public static final Biome SEMI_ARID_DESERT = new BiomeSemiAridDesert();
	public static final Biome OUTBACK = new BiomeOutback();
	public static final Biome COLD_FOREST = new BiomeColdForest(BiomeForest.Type.NORMAL, "Cold Forest");
	public static final Biome COLD_BIRCH_FOREST = new BiomeColdForest(BiomeForest.Type.BIRCH, "Cold Birch Forest");
	public static final Biome COLD_ROOFED_FOREST = new BiomeColdForest(BiomeForest.Type.ROOFED, "Cold Roofed Forest");
	public static final Biome COLD_MEGA_TAIGA = new BiomeColdMegaTaiga(BiomeTaiga.Type.MEGA, "Cold Mega Taiga");
	public static final Biome COLD_MEGA_SPRUCE_TAIGA = new BiomeColdMegaTaiga(BiomeTaiga.Type.MEGA_SPRUCE, "Cold Mega Spruce Taiga");
	public static final Biome BLUE_MUSHROOM_PLAINS = new BiomeBlueMushroomPlains();
	public static final Biome PINK_MUSHROOM_PLAINS = new BiomePinkMushroomPlains();
	public static final Biome FUNGAL_JUNGLE = new BiomeFungalJungle();
	public static final Biome JUNGLE_ARCHIPELAGO = new BiomeJungleArchipelago();
	public static final Biome AEGEAN_ARCHIPELAGO = new BiomeAegeanArchipelago();
	public static final Biome MOUNTAINOUS_ARCHIPELAGO = new BiomeMountainousArchipelago();
	public static final Biome DESERT_ARCHIPELAGO = new BiomeDesertArchipelago();
	public static final Biome ANCIENT_FOREST = new BiomeAncientForest();
	public static final Biome GOLDEN_FOREST = new BiomeGoldenForest();
	public static final Biome CRIMSON_WOODS = new BiomeCrimsonWoods();
	public static final Biome MANGROVE = new BiomeMangrove();
	public static final Biome LUSHFOREST = new BiomeLushForest();
	public static final Biome PRAIRE = new BiomePraire();
	public static final Biome SILKGLADES = new BiomeSilkglades();
	public static final Biome SALT_LAKE = new BiomeSaltLake();
	public static final Biome OAK_FOREST = new BiomeOakForest();
	public static final Biome SAHARA = new BiomeSahara();
	public static final Biome CLIFFS = new BiomeCliffs();
	public static final Biome TROPICAL_FOREST = new BiomeTropicalForest();
	public static final Biome TROPICAL_GRASSLAND = new BiomeTropicalGrassland();
	public static final Biome BLOSSOM_ARCHIPELAGO = new BiomeBlossomArchipelago();
	public static final Biome COLD_ARCHIPELAGO = new BiomeColdArchipelago();
	public static final Biome GREEN_ARCHIPELAGO = new BiomeGreenArchipelago();
	public static final Biome RAINFOREST_ARCHIPELAGO = new BiomeRainforestArchipelago();
	public static final Biome DENSE_SHRUBLAND = new BiomeDenseShrubland();
	public static final Biome AUTUMN_TAIGA = new BiomeAutumnTaiga();
	public static final Biome STONELANDS = new BiomeStonelands();
	public static final Biome CLAYLANDS = new BiomeClaylands();
	public static final Biome BROWN_BEACH = new BiomeBrownBeach();
	public static final Biome DRY_SHRUBLAND = new BiomeDryShrubland();
	public static final Biome TALL_OAK_FOREST = new BiomeTallOakForest();
	
	public static void registerBiomes() {
		
		initBiome(TROPICAL_DESERT, "Tropical_Desert",  6, Config.disableTropicalDesert,BiomeType.DESERT, Type.LUSH, Type.JUNGLE);
		initBiome(GREENEXTREMEHILLS, "Green_Extreme_Hills",  6, Config.disableGreenExtremeHills,BiomeType.WARM, Type.MOUNTAIN, Type.HILLS);
		initBiome(PLATEAU, "Plateau",  4, Config.disablePlateau,BiomeType.WARM, Type.MESA);
		initBiome(STEPPE, "Steppe",  5, Config.disableSteppe,BiomeType.WARM, Type.HILLS);
		initBiome(LAKE, "Lake",  6, Config.disableLake,BiomeType.WARM, Type.WATER);
		initBiome(FROZENLAKE, "Frozen_Lake",  5, Config.disableFrozenLake,BiomeType.ICY, Type.WATER, Type.COLD);
		initBiome(REDPLATEAU, "Red_Plateau",  5, Config.disableRedPlateau,BiomeType.DESERT, Type.DRY, Type.SANDY, Type.MESA);
		initBiome(GRASSLAND, "Grassland", 7, Config.disableGrassland, BiomeType.WARM, Type.PLAINS);
		initBiome(FENS, "Fens", 7, Config.disableFens, BiomeType.WARM, Type.SWAMP);
		initBiome(SHRUBLAND, "Shrubland", 8, Config.disableShrubland, BiomeType.WARM, Type.PLAINS);
		initBiome(TUNDRASPIKES, "Tundra_Spikes", 4, Config.disableTundraSpikes, BiomeType.ICY, Type.WASTELAND, Type.COLD, Type.SNOWY, Type.DRY);
		initBiome(TUNDRA, "Tundra", 5, Config.disableTundra, BiomeType.ICY, Type.WASTELAND, Type.COLD, Type.SNOWY, Type.DRY);
		initBiome(ROCKLAND, "Rockland", 3, Config.disableRockland, BiomeType.WARM, Type.RARE, Type.DEAD, Type.DRY, Type.WASTELAND);
		initBiome(SAHEL, "Sahel", 7, Config.disableSahel, BiomeType.DESERT, Type.HOT, Type.SAVANNA, Type.SANDY);
		initBiome(SANDSTONEDUNES, "Sandstone_Dunes", 6, Config.disableSandstoneDunes, BiomeType.DESERT, Type.SANDY);
		initBiome(SAND_DUNES, "Sand_Dunes", 6, Config.disableSandDunes, BiomeType.DESERT, Type.SANDY);
		initBiome(REDMOUNTAIN, "Red_Mountain", 5, Config.disableRedMountains, BiomeType.DESERT, Type.SANDY, Type.SPARSE, Type.MOUNTAIN);
		initBiome(ALPS, "Alps", 6, Config.disableAlps, BiomeType.ICY, Type.COLD, Type.SPARSE, Type.SNOWY);
		initBiome(HIGHLANDS, "Highlands", 6, Config.disableHighlands, BiomeType.WARM, Type.HILLS, Type.SPARSE);
		initBiome(PINELANDS, "Pinelands", 6, Config.disablePinelands, BiomeType.WARM, Type.HILLS, Type.SPARSE);
		initBiome(GLACIER, "Glacier", 3, Config.disableGlacier, BiomeType.ICY, Type.COLD, Type.SNOWY, Type.DRY);
		initBiome(GREENHILLS, "Green_Hills", 7, Config.disableGreenHills, BiomeType.WARM, Type.HILLS, Type.SPARSE);
		initBiome(RAINFOREST, "Rainforest", 6, Config.disableRainforest, BiomeType.WARM, Type.JUNGLE, Type.LUSH, Type.WET);
		initBiome(MEADOW, "Meadow", 7, Config.disableMeadow, BiomeType.WARM, Type.PLAINS, Type.SPARSE, Type.LUSH);
		initBiome(WOODLANDS, "Woodlands", 7, Config.disableWoodlands, BiomeType.WARM, Type.FOREST);
		initBiome(PINKBEACH, "Pink_Beach", 3, Config.disablePinkBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(REDBEACH, "Red_Beach", 3, Config.disableRedBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(PURPLEBEACH, "Purple_Beach", 3, Config.disablePurpleBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(BLACKBEACH, "Black_Beach", 3, Config.disableBlackBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(BROWN_BEACH, "Brown_Beach", 3, Config.disableBrownBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(GREENBEACH, "Green_Beach", 3, Config.disableGreenBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(WHITEBEACH, "White_Beach", 3, Config.disableWhiteBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(ORANGEBEACH, "Orange_Beach", 3, Config.disableOrangeBeach, BiomeType.WARM, Type.BEACH, Type.WATER);
		initBiome(BLACKDESERT, "Black_Desert", 2, Config.disableBlackDesert, BiomeType.DESERT, Type.DRY, Type.SANDY);
		initBiome(BLACKSAND_DUNES, "BlackSand_Dunes", 2, Config.disableBlackSandDunes, BiomeType.DESERT, Type.DRY, Type.SANDY);
		initBiome(BLUEMOUNTAIN, "Blue_Mountain", 5, Config.disableBlueMountains, BiomeType.ICY, Type.COLD, Type.SPARSE, Type.SNOWY, Type.MOUNTAIN);
		initBiome(GREYMOUNTAIN, "Grey_Mountain",  5, Config.disableGreyMountains,BiomeType.WARM, Type.MOUNTAIN, Type.SPARSE);
		initBiome(CLAYLANDS, "Claylands",  7, Config.disableClaylands,BiomeType.WARM, Type.HILLS, Type.SPARSE, Type.SAVANNA);
		initBiome(STONELANDS, "Stonelands",  7, Config.disableStonelands,BiomeType.WARM, Type.HILLS, Type.SPARSE, Type.SAVANNA);
		initBiome(OVERGROWN_PLAINS, "Overgrown_Plains",  2, Config.disableOvergrownPlains,BiomeType.WARM, Type.PLAINS, Type.JUNGLE, Type.LUSH);
		initBiome(LUSH_SWAMP, "Lush_Swamp",  7, Config.disableLushSwamp,BiomeType.WARM, Type.SWAMP, Type.LUSH, Type.WET);
		initBiome(THICKET, "Thicket",  6, Config.disableThicket,BiomeType.WARM, Type.PLAINS, Type.DENSE, Type.SAVANNA);
		initBiome(BLOSSOM_WOODS, "Blossom_Woods",  7, Config.disableBlossomWoods,BiomeType.WARM, Type.FOREST, Type.MAGICAL);
		initBiome(BLUE_TAIGA, "Blue_Taiga",  6, Config.disableBlueTaiga,BiomeType.COOL, Type.CONIFEROUS);
		initBiome(COLD_BLUE_TAIGA, "Cold_Blue_Taiga",  4, Config.disableColdBlueTaiga,BiomeType.COOL, Type.CONIFEROUS, Type.SNOWY);
		initBiome(MYSTIC_WOODS, "Mystic_Woods", 4, Config.disableMysticWoods, BiomeType.WARM, Type.MAGICAL, Type.FOREST, Type.RARE);
		initBiome(COLD_DESERT, "Cold_Desert", 6, Config.disableColdDesert, BiomeType.ICY, Type.DEAD, Type.COLD, Type.SNOWY);
		initBiome(SPRUCE_WOODS, "Spruce_Woods", 6, Config.disableSpruceWoods, BiomeType.COOL, Type.CONIFEROUS, Type.DENSE);
		initBiome(SEMI_ARID_DESERT, "Semi_Arid_Desert", 6, Config.disableSemiAridDesert, BiomeType.DESERT, Type.DRY, Type.SANDY, Type.SPARSE);
		initBiome(OUTBACK, "Outback", 6, Config.disableOutback, BiomeType.DESERT, Type.DRY, Type.SANDY, Type.SPARSE);
		initBiome(COLD_FOREST, "Cold_Forest", 6, Config.disableColdForest, BiomeType.ICY, Type.COLD, Type.FOREST);
		initBiome(COLD_BIRCH_FOREST, "Cold_Birch_Forest", 5, Config.disableColdBirchForest, BiomeType.ICY, Type.COLD, Type.FOREST);
		initBiome(COLD_ROOFED_FOREST, "Cold_Roofed_Forest", 5, Config.disableColdRoofedForest, BiomeType.ICY, Type.COLD, Type.FOREST);
		initBiome(COLD_MEGA_TAIGA, "Cold_Mega_Taiga", 5, Config.disableColdMegaTaiga, BiomeType.ICY, Type.COLD, Type.CONIFEROUS);
		initBiome(COLD_MEGA_SPRUCE_TAIGA, "Cold_Mega_Spruce_Taiga", 5, Config.disableColdMegaSpruceTaiga, BiomeType.ICY, Type.COLD, Type.CONIFEROUS);
		initBiome(BLUE_MUSHROOM_PLAINS, "Blue_Mushroom_Plains", 1, Config.disableBlueMushroomPlains, BiomeType.WARM, Type.MAGICAL, Type.PLAINS, Type.MUSHROOM);
		initBiome(PINK_MUSHROOM_PLAINS, "Pink_Mushroom_Plains", 1, Config.disablePinkMushroomPlains, BiomeType.WARM, Type.MAGICAL, Type.PLAINS, Type.MUSHROOM);
		initBiome(FUNGAL_JUNGLE, "Fungal_Jungle",  3, Config.disableFungalJungle,BiomeType.WARM, Type.LUSH, Type.JUNGLE, Type.MUSHROOM);
		initBiome(JUNGLE_ARCHIPELAGO, "Jungle_Archipelago",  2, Config.disableJungleArchipelago,BiomeType.WARM, Type.JUNGLE, Type.WATER, Type.OCEAN);
		initBiome(AEGEAN_ARCHIPELAGO, "Aegean_Archipelago",  2, Config.disableAegeanArchipelago,BiomeType.WARM, Type.WATER, Type.OCEAN);
		initBiome(MOUNTAINOUS_ARCHIPELAGO, "Mountainous_Archipelago",  2, Config.disableMountainousArchipelago,BiomeType.WARM, Type.MOUNTAIN, Type.WATER, Type.OCEAN);
		initBiome(DESERT_ARCHIPELAGO, "Desert_Archipelago",  2, Config.disableDesertArchipelago,BiomeType.DESERT, Type.DRY, Type.SANDY, Type.WATER, Type.OCEAN);
		initBiome(ANCIENT_FOREST, "Ancient_Forest",  2, Config.disableAncientForest,BiomeType.WARM, Type.FOREST, Type.MAGICAL);
		initBiome(GOLDEN_FOREST, "Golden_Forest",  4, Config.disableGoldenForest,BiomeType.WARM, Type.FOREST);
		initBiome(MANGROVE, "Mangrove",  5, Config.disableMangrove,BiomeType.WARM, Type.SWAMP);
		initBiome(LUSHFOREST, "Lush_Forest", 6, Config.disableLushForest, BiomeType.WARM, Type.FOREST, Type.LUSH);
		initBiome(PRAIRE, "Praire", 3, Config.disablePraire, BiomeType.WARM, Type.SAVANNA, Type.SPARSE);
		initBiome(SILKGLADES, "Silkglades", 2, Config.disableSilkglades, BiomeType.WARM, Type.FOREST, Type.DRY);
		initBiome(CRIMSON_WOODS, "Crimson_Woods", 4, Config.disableCrimsonWoods, BiomeType.WARM, Type.MAGICAL, Type.FOREST, Type.RARE);
		initBiome(COLDPLATEAU, "Cold_Plateau",  5, Config.disableColdPlateau,BiomeType.COOL, Type.COLD, Type.SNOWY);
		initBiome(FROZENPLATEAU, "Frozen_Plateau",  4, Config.disableFrozenPlateau,BiomeType.ICY, Type.COLD, Type.SNOWY);
		initBiome(GREENPLATEAU, "Green_Plateau",  5, Config.disableGreenPlateau,BiomeType.WARM, Type.LUSH, Type.JUNGLE, Type.RARE);
		initBiome(DRYPLATEAU, "Dry_Plateau",  5, Config.disableDryPlateau,BiomeType.WARM, Type.DRY, Type.SPARSE, Type.SNOWY, Type.MESA);
		initBiome(SALT_LAKE, "Salt_Lake",  3, Config.disableSaltLake,BiomeType.WARM, Type.WATER, Type.DEAD);
		initBiome(OAK_FOREST, "Oak_Forest",  6, Config.disableOakForest,BiomeType.WARM, Type.FOREST);
		initBiome(SAHARA, "Sahara",  3, Config.disableSahara,BiomeType.DESERT, Type.SANDY);
		initBiome(CLIFFS, "Cliffs",  7, Config.disableCliffs,BiomeType.WARM, Type.HILLS);
		initBiome(TROPICAL_FOREST, "Tropical_Forest",  5, Config.disableTropicalForest,BiomeType.WARM, Type.JUNGLE);
		initBiome(TROPICAL_GRASSLAND, "Tropical_Grassland", 4, Config.disableTropicalGrassland, BiomeType.WARM, Type.JUNGLE);
		initBiome(BLOSSOM_ARCHIPELAGO, "Blossom_Archipelago",  2, Config.disableBlossomArchipelago,BiomeType.WARM, Type.WATER, Type.OCEAN);
		initBiome(COLD_ARCHIPELAGO, "Cold_Archipelago",  2, Config.disableColdArchipelago,BiomeType.COOL, Type.WATER, Type.OCEAN);
		initBiome(RAINFOREST_ARCHIPELAGO, "Rainforest_Archipelago",  2, Config.disableRainforestArchipelago,BiomeType.WARM, Type.WATER, Type.OCEAN);
		initBiome(DENSE_SHRUBLAND, "Dense_Shrubland", 5, Config.disableDenseShrubland, BiomeType.WARM, Type.PLAINS, Type.DENSE);
		initBiome(DRY_SHRUBLAND, "Dry_Shrubland", 4, Config.disableDenseShrubland, BiomeType.DESERT, Type.PLAINS, Type.DRY);
		initBiome(AUTUMN_TAIGA, "Autumn_Taiga", 7, Config.disableAutumnTaiga, BiomeType.WARM, Type.CONIFEROUS);
		initBiome(TALL_OAK_FOREST, "Tall_Oak_Forest",  4, Config.disableTallOakForest,BiomeType.WARM, Type.FOREST);
		initBiome(RED_SAND_DUNES, "Red_Sand_Dunes", 4, Config.disableRedSandDunes, BiomeType.DESERT, Type.SANDY);
		initBiome(ORANGE_SAND_DUNES, "Orange_Sand_Dunes", 4, Config.disableOrangeSandDunes, BiomeType.DESERT, Type.SANDY);
	}

	private static Biome initBiome(Biome biome, String name, int weight, boolean disabled, BiomeType biomeType, Type... types)	{
		if (!disabled) {
		biome.setRegistryName(name);
		ForgeRegistries.BIOMES.register(biome);
		System.out.println("Biome Registered");
		BiomeDictionary.addTypes(biome, types);
		BiomeManager.addBiome(biomeType, new BiomeEntry(biome, weight));
		BiomeManager.addSpawnBiome(biome);
		BiomeManager.addStrongholdBiome(biome);
		BiomeManager.addVillageBiome(biome, true);
		System.out.println("Biome Added");
		}
		return biome;
	}
	}
	    